### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by FHantke** [ljr318/Identify_ICO_OotB_Scripts#1]
Hi @ljr318,

looking for the idea behind the `"pl_css_ganrao"` id, I found your project.
I am wondering what your project is about and if you have any idea where this id comes from?
Here is the appearance in your project:
https://github.com/ljr318/Identify_ICO_OotB_Scripts/blob/346a462649a344ce9e7c1f6213fc90de15e97d78/ICO_Htmls/DinnerfulNetwork.html#L2185

Thank you!

**Comment by ljr318** [comment]
Are you a front-end developer? This html file is dumped automatically by python crawler for deep learning training. I'm guessing that this h5 tag id&nbsp;"pl_css_ganrao" is generated by a general H5 framework which helps people with no front-end developing experience to set up a website easily.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ljr318/Identify_ICO_OotB_Scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 凌晨5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[ljr318/Identify_ICO_OotB_Scripts] Question about project (Issue #1)





 
Hi @ljr318,
 
looking for the idea behind the "pl_css_ganrao" id, I found your project.
 I am wondering what your project is about and if you have any idea where this id comes from?
 Here is the appearance in your project:
 https://github.com/ljr318/Identify_ICO_OotB_Scripts/blob/346a462649a344ce9e7c1f6213fc90de15e97d78/ICO_Htmls/DinnerfulNetwork.html#L2185
 
Thank you!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FHantke** [comment]
Hi. No, I am not a front-end developer, but a security researcher. I found this id in my data only on presumably malicious websites and thought, maybe you have an id what these websites are. But it seems that you also only obtained the data using a crawler like I did. Anyway, thank you :)
